namespace EXAMEN_SOFTWARE_FIALLOS_GUEVRA.Interfaces
{
    public interface INotificationChannel_FG
    {
        //PRINCIPIO SOLID: SLP : CADA INTERFAZ TIENE UNA SOLA RESPONSABILIDAD, METODO QUE SE ENCARGA DE HACER EL CONTRATO PARA LAS NOTIFICACIONES
        //PRINCIPIO SOLID : ICP: NINGUNA INTERFAZ TIENE METODOS QUE NO SEAN RELEVANTES PARA LAS CLASES QUE LES IMPLEMENTAN 

        string SendNotification_FG(string message, string user);
    }
}
