namespace EXAMEN_SOFTWARE_FIALLOS_GUEVRA.Interfaces
{
    public interface IOutput_FG
    {
        //PRINCIPIO SOLID: SLP : CADA INTERFAZ TIENE UNA SOLA RESPONSABILIDAD, METODO QUE SE ENCARGA DE HACER EL CONTRATO PARA LAS NOTIFICACIONES
        //PRINCIPIO SOLID : OCP : ABIERTO PARA EXTENSIONES Y CERRADO PARA MODIFICACIONES , SE PUEDE AGREGAR NUEVOS METODOS SIN MODIFCAR ESTA INTERFAZ
        void ShowResult_FG(Models.PaymentResult_FG result);
    }
}
