namespace EXAMEN_SOFTWARE_FIALLOS_GUEVRA.Interfaces
{
    public interface IOutput_FG
    {
        //PRINCIPIO SOLID: SLP : CADA INTERFAZ TIENE UNA SOLA RESPONSABILIDAD, METODO QUE SE ENCARGA DE HACER EL CONTRATO DE MOSTRAR EL RESULTADO
        //PRINCIPIO SOLID : DIP : PERIMITEC¿ CAMBIAR LA FORMA DE COMO SE MUESTRA LOS RESULTADOS  
        void ShowResult_FG(Models.PaymentResult_FG result);
    }
}
