using System.Globalization;

namespace EXAMEN_SOFTWARE_FIALLOS_GUEVRA.Interfaces
{
    public interface IPaymentMethod_FG
    {
        //PRINCIPIO SOLID: SLP : CADA INTERFAZ TIENE UNA SOLA RESPONSABILIDAD, METODO QUE SE ENCARGA DE HACER EL CONTRATO PARA EL PROCESO DE PAGO
        //PRINCIPIO SOLID : ICP: NINGUNA INTERFAZ TIENE METODOS QUE NO SEAN RELEVANTES PARA LAS CLASES QUE LES IMPLEMENTAN 
        string ProcessPayment_FG(decimal amount, string user);
    }
}
